# -*- coding: utf-8 -*-
"""HealHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10DVPavNTtgqurcyjuF-etvxxzVaZYZeE

SentenceTransformer model and a vector database (ChromaDB) are utilized to create a searchable database of diseases, their associated symptoms and treatments.

Two datasets are processed, embedding their text descriptions and storing them in separate ChromaDB collections. A disease synonyms dictionary is also created to help with searching.
"""

!pip install -q pandas sentence-transformers chromadb

import pandas as pd
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.config import Settings

import pandas as pd

# Dataset 1
url1 = "https://huggingface.co/datasets/QuyenAnhDE/Diseases_Symptoms/resolve/main/Diseases_Symptoms.csv"
df1 = pd.read_csv(url1)
df1.head()

# Dataset 2
url2 = "https://huggingface.co/datasets/TaruK/IISCProject/resolve/main/Diseases%26Symptoms.csv"
df2 = pd.read_csv(url2)
df2.head()

# Embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")
client = chromadb.Client(Settings())

# --- Dataset 1 ---
df1_copy = df1.copy()
df1_copy["combined"] = df1_copy["Name"].astype(str) + ": " + df1_copy["Symptoms"].astype(str) + " | Treatment: " + df1_copy["Treatments"].astype(str)
texts1 = df1_copy["combined"].dropna().tolist()

embeddings1 = model.encode(texts1, show_progress_bar=True)

if "healhub_dataset1" not in [col.name for col in client.list_collections()]:
    collection1 = client.create_collection("healhub_dataset1")
else:
    collection1 = client.get_collection("healhub_dataset1")

for i, (text, emb) in enumerate(zip(texts1, embeddings1)):
    collection1.add(documents=[text], embeddings=[emb.tolist()], ids=[f"ds1_{i}"])

# --- Dataset 2 ---
df2_copy = df2.copy()

symptom_cols = df2_copy.columns.drop("diseases")
df2_copy["SymptomsText"] = df2_copy[symptom_cols].apply(
    lambda row: ", ".join([symptom for symptom in symptom_cols if row[symptom] == 1]), axis=1
)
df2_copy["combined"] = df2_copy["diseases"].astype(str) + ": " + df2_copy["SymptomsText"]
texts2 = df2_copy["combined"].dropna().tolist()

embeddings2 = model.encode(texts2, show_progress_bar=True)

if "healhub_dataset2" not in [col.name for col in client.list_collections()]:
    collection2 = client.create_collection("healhub_dataset2")
else:
    collection2 = client.get_collection("healhub_dataset2")


for i, (text, emb) in enumerate(zip(texts2, embeddings2)):
    collection2.add(documents=[text], embeddings=[emb.tolist()], ids=[f"ds2_{i}"])

# Dictionary of Diseases and their common synonyms
synonyms = {
    "depression": ["sadness", "low mood", "depressed mood", "clinical depression"],
    "headache": ["migraine", "cephalalgia", "head pain"],
    "panic disorder": ["anxiety disorder", "panic attacks", "panic syndrome"],
    "vocal cord polyp": ["laryngeal polyp", "vocal fold polyp", "voice box polyp"],
    "turner syndrome": ["gonadal dysgenesis", "Turner's syndrome", "45,X syndrome"],
    "cryptorchidism": ["undescended testicle", "undescended testes", "testicular maldescent"],
    "poisoning due to ethylene glycol": ["ethylene glycol toxicity", "antifreeze poisoning", "ethylene glycol intoxication"],
    "atrophic vaginitis": ["vaginal atrophy", "postmenopausal vaginitis", "atrophic vaginosis"],
    "fracture of the hand": ["hand fracture", "broken hand", "metacarpal fracture"],
    "cellulitis or abscess of mouth": ["oral cellulitis", "mouth abscess", "oral abscess"],
    "eye alignment disorder": ["strabismus", "eye misalignment", "ocular misalignment"],
    "headache after lumbar puncture": ["post-lumbar puncture headache", "spinal tap headache", "post-dural puncture headache"],
    "pyloric stenosis": ["infantile hypertrophic pyloric stenosis", "gastric outlet obstruction", "pyloric obstruction"],
    "salivary gland disorder": ["sialadenitis", "salivary gland disease", "salivary gland infection"],
    "osteochondrosis": ["bone growth disorder", "osteochondritis", "cartilage disorder"],
    "injury to the knee": ["knee injury", "knee trauma", "patellar injury"],
    "metabolic disorder": ["metabolic disease", "metabolic syndrome", "metabolic dysfunction"],
    "vaginitis": ["vaginal infection", "vaginal inflammation", "vaginal irritation"],
    "sick sinus syndrome": ["sinus node dysfunction", "sinus node disease", "sinus node disorder"],
    "tinnitus of unknown cause": ["idiopathic tinnitus", "unexplained tinnitus", "unknown cause tinnitus"],
    "glaucoma": ["ocular hypertension", "optic neuropathy", "glaucomatous optic neuropathy"],
    "eating disorder": ["disordered eating", "feeding disorder", "nutritional disorder"],
    "transient ischemic attack": ["mini-stroke", "TIA", "temporary stroke"],
    "pyelonephritis": ["kidney infection", "renal infection", "pyelitis"],
    "rotator cuff injury": ["shoulder injury", "rotator cuff tear", "shoulder tear"],
    "chronic pain disorder": ["persistent pain syndrome", "chronic pain syndrome", "long-term pain disorder"],
    "problem during pregnancy": ["pregnancy complication", "gestational issue", "prenatal problem"],
    "liver cancer": ["hepatic carcinoma", "hepatocellular carcinoma", "liver malignancy"],
    "atelectasis": ["lung collapse", "pulmonary collapse", "alveolar collapse"],
    "injury to the hand": ["hand trauma", "hand injury", "manual injury"],
    "choledocholithiasis": ["bile duct stones", "common bile duct stones", "CBD stones"],
    "injury to the hip": ["hip trauma", "hip injury", "pelvic injury"],
    "cirrhosis": ["liver cirrhosis", "hepatic cirrhosis", "liver fibrosis"],
    "thoracic aortic aneurysm": ["chest aortic aneurysm", "thoracic aneurysm", "aortic aneurysm"],
    "subdural hemorrhage": ["subdural hematoma", "brain bleed", "subdural bleed"],
    "diabetic retinopathy": ["diabetes eye disease", "diabetic eye disease", "diabetic retinal disease"],
    "fibromyalgia": ["chronic pain syndrome", "fibrositis", "fibromyositis"],
    "ischemia of the bowel": ["intestinal ischemia", "bowel ischemia", "gut ischemia"],
    "fetal alcohol syndrome": ["FAS", "alcohol-related birth defects", "prenatal alcohol exposure"],
    "peritonitis": ["abdominal infection", "peritoneal infection", "abdominal inflammation"],
    "injury to the abdomen": ["abdominal trauma", "abdominal injury", "belly injury"],
    "acute pancreatitis": ["pancreatic inflammation", "pancreatic attack", "pancreatic infection"],
    "thrombophlebitis": ["vein inflammation", "phlebitis", "vein thrombosis"],
    "asthma": ["bronchial asthma", "reactive airway disease", "asthmatic condition"],
    "foreign body in the vagina": ["vaginal foreign object", "vaginal foreign body", "vaginal obstruction"],
    "restless leg syndrome": ["RLS", "Willis-Ekbom disease", "restless legs"],
    "emphysema": ["COPD", "chronic obstructive pulmonary disease", "pulmonary emphysema"],
    "cysticercosis": ["tapeworm infection", "cysticercus infection", "parasitic infection"],
    "induced abortion": ["medical abortion", "surgical abortion", "termination of pregnancy"],
    "teething syndrome": ["teething pain", "teething discomfort", "teething issues"],
    "infectious gastroenteritis": ["stomach flu", "intestinal infection", "gastrointestinal infection"],
    "acute sinusitis": ["sinus infection", "sinus inflammation", "sinus disease"],
    "substance-related mental disorder": ["drug-induced mental disorder", "substance abuse disorder", "substance-induced disorder"],
    "postpartum depression": ["postnatal depression", "post-birth depression", "postpartum mood disorder"],
    "coronary atherosclerosis": ["heart artery disease", "coronary artery disease", "arterial plaque"],
    "spondylitis": ["spinal inflammation", "vertebral inflammation", "spinal arthritis"],
    "pituitary adenoma": ["pituitary tumor", "pituitary growth", "pituitary neoplasm"],
    "uterine fibroids": ["leiomyomas", "myomas", "fibroid tumors"],
    "idiopathic nonmenstrual bleeding": ["abnormal uterine bleeding", "nonmenstrual bleeding", "unexplained uterine bleeding"],
    "chalazion": ["eyelid cyst", "meibomian cyst", "eyelid bump"],
    "ovarian torsion": ["twisted ovary", "ovarian twist", "ovarian rotation"],
    "retinopathy due to high blood pressure": ["hypertensive retinopathy", "blood pressure eye disease", "hypertension-related eye disease"],
    "vaginal yeast infection": ["candidiasis", "vaginal thrush", "vaginal fungal infection"],
    "mastoiditis": ["mastoid infection", "mastoid inflammation", "ear bone infection"],
    "lung contusion": ["pulmonary contusion", "lung bruise", "lung injury"],
    "hypertrophic obstructive cardiomyopathy (hocm)": ["HOCM", "heart muscle disease", "cardiomyopathy"],
    "ingrown toe nail": ["onychocryptosis", "toe nail infection", "toe nail inflammation"],
    "pulmonary eosinophilia": ["lung eosinophilia", "eosinophilic lung disease", "eosinophilic pneumonia"],
    "corneal disorder": ["corneal disease", "corneal condition", "corneal pathology"],
    "foreign body in the gastrointestinal tract": ["GI foreign object", "GI foreign body", "intestinal obstruction"],
    "endophthalmitis": ["eye infection", "ocular infection", "intraocular infection"],
    "intestinal malabsorption": ["malabsorption syndrome", "intestinal absorption disorder", "nutrient absorption disorder"],
    "viral warts": ["verrucae", "skin warts", "cutaneous warts"],
    "hyperhidrosis": ["excessive sweating", "sweat disorder", "sweating disorder"],
    "stroke": ["cerebrovascular accident", "brain attack", "cerebral infarction"],
    "pilonidal cyst": ["pilonidal abscess", "pilonidal sinus", "tailbone cyst"],
    "crushing injury": ["compression injury", "crush trauma", "crush injury"],
    "normal pressure hydrocephalus": ["NPH", "hydrocephalus", "brain fluid disorder"],
    "alopecia": ["hair loss", "baldness", "hair thinning"],
    "hashimoto thyroiditis": ["autoimmune thyroiditis", "Hashimoto's disease", "chronic thyroiditis"],
    "flat feet": ["pes planus", "fallen arches", "low arches"],
    "nonalcoholic liver disease (nash)": ["nonalcoholic steatohepatitis", "NASH", "fatty liver disease"],
    "hemarthrosis": ["joint bleeding", "hemorrhagic arthritis", "joint hemorrhage"],
    "pelvic organ prolapse": ["POP", "pelvic prolapse", "organ prolapse"],
    "fracture of the arm": ["arm fracture", "broken arm", "humerus fracture"],
    "coagulation (bleeding) disorder": ["bleeding disorder", "clotting disorder", "coagulopathy"],
    "intracranial hemorrhage": ["brain bleed", "cerebral hemorrhage", "intracerebral hemorrhage"],
    "hyperkalemia": ["high potassium", "elevated potassium", "potassium excess"],
    "cornea infection": ["corneal infection", "keratitis", "corneal ulcer"],
    "abscess of the lung": ["lung abscess", "pulmonary abscess", "lung infection"],
    "dengue fever": ["dengue", "breakbone fever", "dengue virus infection"],
    "chronic sinusitis": ["chronic sinus infection", "chronic rhinosinusitis", "persistent sinusitis"],
    "cholesteatoma": ["ear cyst", "middle ear cholesteatoma", "cholesteatoma of the ear"],
    "volvulus": ["intestinal twisting", "bowel volvulus", "gut twisting"],
    "injury to the finger": ["finger injury", "finger trauma", "digital injury"],
    "poisoning due to analgesics": ["analgesic poisoning", "painkiller overdose", "analgesic overdose"],
    "atrial fibrillation": ["AFib", "AF", "irregular heartbeat"],
    "pinworm infection": ["enterobiasis", "oxyuriasis", "pinworm infestation"],
    "urethral valves": ["posterior urethral valves", "PUV", "urethral obstruction"],
    "open wound of the neck": ["neck wound", "cervical wound", "neck laceration"],
    "achalasia": ["esophageal achalasia", "cardiospasm", "esophageal motility disorder"],
    "conductive hearing loss": ["CHL", "middle ear hearing loss", "conductive deafness"],
    "abdominal hernia": ["hernia", "abdominal wall hernia", "ventral hernia"],
    "cerebral palsy": ["CP", "spastic paralysis", "cerebral paralysis"],
    "marijuana abuse": ["cannabis abuse", "marijuana addiction", "cannabis use disorder"],
    "cryptococcosis": ["cryptococcal infection", "cryptococcal meningitis", "cryptococcus infection"],
    "obesity": ["overweight", "excess weight", "adiposity"],
    "indigestion": ["dyspepsia", "upset stomach", "stomach discomfort"],
    "bursitis": ["joint inflammation", "bursa inflammation", "bursal inflammation"],
    "esophageal cancer": ["esophageal carcinoma", "esophageal malignancy", "esophageal tumor"],
    "pulmonary congestion": ["lung congestion", "pulmonary edema", "lung fluid"],
    "juvenile rheumatoid arthritis": ["JRA", "juvenile idiopathic arthritis", "juvenile arthritis"],
    "actinic keratosis": ["solar keratosis", "sun-induced keratosis", "precancerous skin lesion"],
    "acute otitis media": ["AOM", "middle ear infection", "ear infection"],
    "astigmatism": ["refractive error", "corneal astigmatism", "lens astigmatism"],
    "tuberous sclerosis": ["TSC", "tuberous sclerosis complex", "Bourneville disease"],
    "empyema": ["pleural empyema", "pyothorax", "pleural infection"],
    "presbyacusis": ["age-related hearing loss", "presbycusis", "senile deafness"],
    "neonatal jaundice": ["newborn jaundice", "infant jaundice", "hyperbilirubinemia"],
    "chronic obstructive pulmonary disease (copd)": ["COPD", "chronic bronchitis", "emphysema"],
    "dislocation of the elbow": ["elbow dislocation", "elbow luxation", "elbow joint dislocation"],
    "spondylosis": ["spinal osteoarthritis", "degenerative disc disease", "vertebral osteoarthritis"],
    "herpangina": ["mouth blisters", "coxsackievirus infection", "enterovirus infection"],
    "injury to the shoulder": ["shoulder injury", "shoulder trauma", "shoulder damage"],
    "poisoning due to antidepressants": ["antidepressant overdose", "antidepressant toxicity", "antidepressant poisoning"],
    "infection of open wound": ["wound infection", "infected wound", "open wound infection"],
    "deep vein thrombosis (dvt)": ["DVT", "blood clot in leg", "venous thrombosis"],
    "protein deficiency": ["protein malnutrition", "hypoproteinemia", "protein-energy malnutrition"],
    "myoclonus": ["muscle jerks", "involuntary muscle contractions", "myoclonic jerks"],
    "bone spur of the calcaneous": ["heel spur", "calcaneal spur", "heel bone spur"],
    "von willebrand disease": ["VWD", "von Willebrand's disease", "bleeding disorder"],
    "open wound of the back": ["back wound", "dorsal wound", "back laceration"],
    "heart block": ["AV block", "atrioventricular block", "cardiac block"],
    "colonic polyp": ["colon polyp", "intestinal polyp", "colorectal polyp"],
    "magnesium deficiency": ["hypomagnesemia", "low magnesium", "magnesium depletion"],
    "female infertility of unknown cause": ["unexplained infertility", "idiopathic infertility", "unknown cause infertility"],
    "pericarditis": ["heart lining inflammation", "pericardial inflammation", "pericardium inflammation"],
    "attention deficit hyperactivity disorder (adhd)": ["ADHD", "attention deficit disorder", "hyperactivity disorder"],
    "pulmonic valve disease": ["pulmonary valve disease", "pulmonary valve disorder", "pulmonic valve disorder"],
    "tietze syndrome": ["costochondritis", "chest wall pain", "Tietze's disease"],
    "cranial nerve palsy": ["cranial neuropathy", "cranial nerve paralysis", "cranial nerve dysfunction"],
    "injury to the arm": ["arm injury", "arm trauma", "brachial injury"],
    "conversion disorder": ["functional neurological symptom disorder", "psychogenic disorder", "hysteria"],
    "complex regional pain syndrome": ["CRPS", "reflex sympathetic dystrophy", "chronic pain syndrome"],
    "otosclerosis": ["ear bone disease", "middle ear sclerosis", "stapedial otosclerosis"],
    "injury to the trunk": ["trunk injury", "torso injury", "body injury"],
    "hypothyroidism": ["underactive thyroid", "low thyroid", "thyroid deficiency"],
    "primary insomnia": ["chronic insomnia", "idiopathic insomnia", "persistent insomnia"],
    "lice": ["pediculosis", "head lice", "body lice"],
    "vitamin b12 deficiency": ["cobalamin deficiency", "B12 deficiency", "pernicious anemia"],
    "diabetes": ["diabetes mellitus", "high blood sugar", "hyperglycemia"],
    "vulvodynia": ["vulvar pain", "chronic vulvar pain", "vulvar discomfort"],
    "endometriosis": ["endometrial disease", "endometrial growth", "pelvic endometriosis"],
    "vasculitis": ["blood vessel inflammation", "vascular inflammation", "angiitis"],
    "concussion": ["mild traumatic brain injury", "MTBI", "brain concussion"],
    "oral leukoplakia": ["mouth leukoplakia", "oral white patches", "leukoplakia of the mouth"],
    "chronic kidney disease": ["CKD", "chronic renal disease", "chronic kidney failure"],
    "bladder disorder": ["bladder disease", "bladder dysfunction", "bladder condition"],
    "chorioretinitis": ["retinochoroiditis", "choroiditis", "retinal inflammation"],
    "priapism": ["persistent erection", "prolonged erection", "erectile disorder"],
    "myositis": ["muscle inflammation", "muscle disease", "inflammatory myopathy"],
    "mononucleosis": ["mono", "glandular fever", "infectious mononucleosis"],
    "neuralgia": ["nerve pain", "neuropathic pain", "nerve disorder"],
    "polycystic kidney disease": ["PKD", "cystic kidney disease", "polycystic renal disease"],
    "bipolar disorder": ["manic-depressive illness", "bipolar affective disorder", "bipolar mood disorder"],
    "amyloidosis": ["amyloid disease", "protein deposition disease", "amyloid disorder"],
    "chronic inflammatory demyelinating polyneuropathy (cidp)": ["CIDP", "chronic demyelinating neuropathy", "chronic inflammatory neuropathy"],
    "gastroesophageal reflux disease (gerd)": ["GERD", "acid reflux", "heartburn"],
    "vitreous hemorrhage": ["eye bleeding", "vitreous bleeding", "intraocular hemorrhage"],
    "poisoning due to antimicrobial drugs": ["antibiotic poisoning", "antimicrobial toxicity", "drug-induced poisoning"],
    "open wound of the mouth": ["oral wound", "mouth laceration", "oral injury"],
    "scleroderma": ["systemic sclerosis", "skin fibrosis", "autoimmune skin disease"],
    "myasthenia gravis": ["MG", "neuromuscular disorder", "muscle weakness disease"],
    "hypoglycemia": ["low blood sugar", "low glucose", "blood sugar deficiency"],
    "idiopathic absence of menstruation": ["amenorrhea", "menstrual absence", "no periods"],
    "dislocation of the ankle": ["ankle dislocation", "ankle joint dislocation", "ankle luxation"],
    "carbon monoxide poisoning": ["CO poisoning", "carbon monoxide toxicity", "CO intoxication"],
    "panic attack": ["anxiety attack", "panic episode", "acute anxiety"],
    "plantar fasciitis": ["heel pain", "foot inflammation", "plantar fascia pain"],
    "hyperopia": ["farsightedness", "hypermetropia", "long-sightedness"],
    "poisoning due to sedatives": ["sedative overdose", "sedative toxicity", "sedative poisoning"],
    "pemphigus": ["autoimmune blistering disease", "skin blistering", "pemphigus vulgaris"],
    "peyronie disease": ["penile curvature", "penile fibrosis", "penile deformity"],
    "hiatal hernia": ["stomach hernia", "diaphragmatic hernia", "esophageal hernia"],
    "extrapyramidal effect of drugs": ["drug-induced movement disorder", "extrapyramidal symptoms", "EPS"],
    "meniere disease": ["inner ear disorder", "vertigo disease", "Meniere's syndrome"],
    "anal fissure": ["rectal tear", "anal tear", "anal ulcer"],
    "allergy": ["hypersensitivity", "allergic reaction", "immune response"],
    "chronic otitis media": ["chronic ear infection", "persistent otitis media", "chronic middle ear infection"],
    "fracture of the finger": ["finger fracture", "broken finger", "digital fracture"],
    "hirschsprung disease": ["congenital megacolon", "intestinal blockage", "aganglionic megacolon"],
    "polymyalgia rheumatica": ["PMR", "muscle pain syndrome", "rheumatic muscle pain"],
    "lymphedema": ["lymphatic swelling", "lymphatic obstruction", "lymph fluid buildup"],
    "bladder cancer": ["bladder carcinoma", "bladder malignancy", "urothelial cancer"],
    "acute bronchospasm": ["bronchial spasm", "airway spasm", "bronchial constriction"],
    "acute glaucoma": ["sudden glaucoma", "acute angle-closure glaucoma", "rapid-onset glaucoma"],
    "open wound of the chest": ["chest wound", "thoracic wound", "chest laceration"],
    "dislocation of the patella": ["kneecap dislocation", "patellar dislocation", "kneecap luxation"],
    "sciatica": ["sciatic nerve pain", "sciatic neuropathy", "sciatic nerve disorder"],
    "hypercalcemia": ["high calcium", "elevated calcium", "calcium excess"],
    "stress incontinence": ["urinary stress incontinence", "stress-related incontinence", "stress-induced incontinence"],
    "varicose veins": ["venous insufficiency", "varicosities", "swollen veins"],
    "benign kidney cyst": ["renal cyst", "kidney cyst", "non-cancerous kidney cyst"],
    "hydrocele of the testicle": ["testicular hydrocele", "scrotal swelling", "fluid-filled testicle"],
    "degenerative disc disease": ["DDD", "spinal degeneration", "disc degeneration"],
    "hirsutism": ["excessive hair growth", "hair overgrowth", "androgenic hair growth"],
    "dislocation of the foot": ["foot dislocation", "foot joint dislocation", "foot luxation"],
    "hydronephrosis": ["kidney swelling", "renal pelvis dilation", "kidney fluid buildup"],
    "diverticulosis": ["intestinal diverticula", "colon diverticula", "diverticular disease"],
    "pain after an operation": ["postoperative pain", "surgical pain", "post-surgery pain"],
    "huntington disease": ["HD", "Huntington's chorea", "neurodegenerative disorder"],
    "lymphoma": ["lymphatic cancer", "lymph node cancer", "lymphatic malignancy"],
    "dermatitis due to sun exposure": ["sun dermatitis", "solar dermatitis", "sun-induced skin inflammation"],
    "anemia due to chronic kidney disease": ["renal anemia", "kidney disease anemia", "CKD-related anemia"],
    "injury to internal organ": ["internal organ injury", "organ trauma", "internal organ damage"],
    "scleritis": ["eye inflammation", "scleral inflammation", "ocular scleritis"],
    "pterygium": ["eye growth", "ocular pterygium", "conjunctival growth"],
    "fungal infection of the skin": ["cutaneous fungal infection", "skin mycosis", "dermatophyte infection"],
    "insulin overdose": ["insulin toxicity", "excess insulin", "insulin shock"],
    "syndrome of inappropriate secretion of adh (siadh)": ["SIADH", "ADH excess", "antidiuretic hormone disorder"],
    "foreign body in the ear": ["ear foreign object", "ear obstruction", "ear blockage"],
    "premenstrual tension syndrome": ["PMS", "premenstrual syndrome", "premenstrual disorder"],
    "orbital cellulitis": ["eye socket infection", "orbital infection", "eye socket inflammation"],
    "injury to the leg": ["leg injury", "leg trauma", "lower limb injury"],
    "hepatic encephalopathy": ["liver brain disorder", "hepatic brain dysfunction", "liver-induced encephalopathy"],
    "bone cancer": ["osteosarcoma", "bone malignancy", "bone tumor"],
    "syringomyelia": ["spinal cyst", "spinal cord cyst", "syrinx"],
    "pulmonary fibrosis": ["lung fibrosis", "interstitial lung disease", "lung scarring"],
    "mitral valve disease": ["mitral valve disorder", "mitral valve insufficiency", "mitral valve regurgitation"],
    "parkinson disease": ["PD", "Parkinson's disease", "neurodegenerative disorder"],
    "gout": ["gouty arthritis", "uric acid arthritis", "gouty joint inflammation"],
    "otitis media": ["middle ear infection", "ear infection", "otitis"],
    "drug abuse (opioids)": ["opioid addiction", "opioid use disorder", "opioid dependence"],
    "myelodysplastic syndrome": ["MDS", "bone marrow disorder", "myelodysplasia"],
    "fracture of the shoulder": ["shoulder fracture", "broken shoulder", "humerus fracture"],
    "acute kidney injury": ["AKI", "acute renal failure", "acute kidney failure"],
    "threatened pregnancy": ["pregnancy complication", "gestational threat", "pregnancy risk"],
    "intracranial abscess": ["brain abscess", "cerebral abscess", "intracerebral abscess"],
    "gum disease": ["periodontal disease", "gingivitis", "periodontitis"],
    "open wound from surgical incision": ["surgical wound", "post-surgical wound", "incision wound"],
    "gastrointestinal hemorrhage": ["GI bleeding", "intestinal bleeding", "gastrointestinal bleeding"],
    "seborrheic dermatitis": ["seborrhea", "scalp dermatitis", "seborrheic eczema"],
    "drug abuse (methamphetamine)": ["meth addiction", "meth use disorder", "meth dependence"],
    "torticollis": ["neck muscle spasm", "wry neck", "neck stiffness"],
    "poisoning due to antihypertensives": ["antihypertensive overdose", "blood pressure medication poisoning", "antihypertensive toxicity"],
    "tension headache": ["stress headache", "muscle tension headache", "tension-type headache"],
    "alcohol intoxication": ["alcohol poisoning", "alcohol overdose", "ethanol intoxication"],
    "scurvy": ["vitamin C deficiency", "ascorbic acid deficiency", "nutritional deficiency"],
    "narcolepsy": ["sleep disorder", "excessive daytime sleepiness", "narcoleptic syndrome"],
    "food allergy": ["food hypersensitivity", "food intolerance", "allergic reaction to food"],
    "labyrinthitis": ["inner ear infection", "vestibular neuritis", "inner ear inflammation"],
    "anxiety": ["anxiety disorder", "nervousness", "anxiousness"],
    "impulse control disorder": ["ICD", "behavioral disorder", "impulsivity disorder"],
    "stenosis of the tear duct": ["tear duct blockage", "nasolacrimal duct stenosis", "lacrimal duct obstruction"],
    "abscess of nose": ["nasal abscess", "nose infection", "nasal infection"],
    "omphalitis": ["umbilical infection", "navel infection", "umbilical inflammation"],
    "leukemia": ["blood cancer"],
    "bell palsy": ["facial paralysis", "facial nerve palsy", "Bell's palsy"],
    "conjunctivitis due to allergy": ["allergic conjunctivitis", "eye allergy", "allergic eye inflammation"],
    "drug reaction": ["adverse drug reaction", "drug side effect", "medication reaction"],
    "adrenal cancer": ["adrenal carcinoma", "adrenal gland cancer", "adrenal malignancy"],
    "myopia": ["nearsightedness", "short-sightedness", "myopic vision"],
    "osteoarthritis": ["degenerative joint disease", "OA", "joint arthritis"],
    "thyroid disease": ["thyroid disorder", "thyroid dysfunction", "thyroid condition"],
    "pharyngitis": ["sore throat", "throat infection", "pharyngeal inflammation"],
    "chronic rheumatic fever": ["rheumatic heart disease", "chronic rheumatic heart disease", "rheumatic fever"],
    "hypocalcemia": ["low calcium", "calcium deficiency", "hypocalcemic condition"],
    "macular degeneration": ["age-related macular degeneration", "AMD", "macular disease"],
    "pneumonia": ["lung infection", "pulmonary infection", "pneumonitis"],
    "cold sore": ["herpes labialis", "oral herpes", "fever blister"],
    "premature ventricular contractions (pvcs)": ["PVCs", "ventricular ectopy", "ventricular premature beats"],
    "testicular cancer": ["testicular carcinoma", "testicular malignancy", "testicular tumor"],
    "hydrocephalus": ["water on the brain", "brain fluid buildup", "hydrocephaly"],
    "breast cancer": ["breast carcinoma", "breast malignancy", "mammary cancer"],
    "anemia due to malignancy": ["cancer-related anemia", "malignant anemia", "tumor-associated anemia"],
    "esophageal varices": ["esophageal veins", "esophageal vein swelling", "esophageal vein dilation"],
    "endometrial cancer": ["uterine cancer", "endometrial carcinoma", "uterine malignancy"],
    "cystic fibrosis": ["CF", "mucoviscidosis", "cystic fibrosis disease"],
    "intertrigo (skin condition)": ["skin fold rash", "intertriginous dermatitis", "skin fold inflammation"],
    "parathyroid adenoma": ["parathyroid tumor", "parathyroid gland tumor", "parathyroid growth"],
    "glucocorticoid deficiency": ["cortisol deficiency", "adrenal insufficiency", "glucocorticoid insufficiency"],
    "temporomandibular joint disorder": ["TMJ disorder", "jaw joint disorder", "TMJ dysfunction"],
    "wilson disease": ["hepatolenticular degeneration", "Wilson's disease", "copper storage disease"],
    "vesicoureteral reflux": ["VUR", "urinary reflux", "vesicoureteric reflux"],
    "vitamin a deficiency": ["hypovitaminosis A", "retinol deficiency", "vitamin A insufficiency"],
    "gonorrhea": ["gonococcal infection", "gonococcal disease", "Neisseria gonorrhoeae infection"],
    "fracture of the rib": ["rib fracture", "broken rib", "rib break"],
    "ependymoma": ["ependymal tumor", "ependymal neoplasm", "ependymal cancer"],
    "hepatitis due to a toxin": ["toxic hepatitis", "toxin-induced hepatitis", "chemical hepatitis"],
    "vaginal cyst": ["vaginal lump", "vaginal nodule", "vaginal sac"],
    "open wound of the shoulder": ["shoulder wound", "shoulder laceration", "shoulder cut"],
    "ectopic pregnancy": ["tubal pregnancy", "extrauterine pregnancy", "ectopic gestation"],
    "chronic knee pain": ["persistent knee pain", "long-term knee pain", "chronic knee discomfort"],
    "pinguecula": ["eye growth", "conjunctival growth", "pingueculae"],
    "hypergammaglobulinemia": ["high gamma globulin", "elevated gamma globulin", "gamma globulin excess"],
    "alcohol abuse": ["alcohol addiction", "alcohol use disorder", "alcohol dependence"],
    "carpal tunnel syndrome": ["CTS", "median nerve compression", "carpal tunnel disorder"],
    "pituitary disorder": ["pituitary gland disorder", "pituitary dysfunction", "pituitary disease"],
    "kidney stone": ["renal calculus", "nephrolithiasis", "kidney calculus"],
    "autism": ["autism spectrum disorder", "ASD", "autistic disorder"],
    "cat scratch disease": ["CSD", "Bartonella infection", "cat scratch fever"],
    "chronic glaucoma": ["long-term glaucoma", "persistent glaucoma", "chronic eye pressure"],
    "retinal detachment": ["detached retina", "retinal separation", "retina detachment"],
    "aplastic anemia": ["bone marrow failure", "aplastic disorder", "pancytopenia"],
    "overflow incontinence": ["urinary overflow incontinence", "overflow bladder", "overflow urinary incontinence"],
    "hemolytic anemia": ["red blood cell destruction", "hemolysis", "hemolytic disorder"],
    "lateral epicondylitis (tennis elbow)": ["tennis elbow", "lateral elbow pain", "lateral epicondylalgia"],
    "open wound of the eye": ["eye wound", "ocular wound", "eye laceration"],
    "syphilis": ["Treponema pallidum infection", "syphilitic infection", "syphilitic disease"],
    "diabetic kidney disease": ["diabetic nephropathy", "diabetic renal disease", "diabetic kidney disorder"],
    "nose disorder": ["nasal disorder", "nasal condition", "nose disease"],
    "drug withdrawal": ["substance withdrawal", "withdrawal syndrome", "drug detox"],
    "dental caries": ["tooth decay", "cavities", "dental cavities"],
    "hypercholesterolemia": ["high cholesterol", "elevated cholesterol", "cholesterol excess"],
    "fracture of the patella": ["kneecap fracture", "patellar fracture", "broken kneecap"],
    "kidney failure": ["renal failure", "kidney insufficiency", "renal insufficiency"],
    "fracture of the neck": ["neck fracture", "cervical fracture", "broken neck"],
    "muscle spasm": ["muscle cramp", "muscle contraction", "muscle twitch"],
    "hemophilia": ["bleeding disorder", "coagulation disorder", "hemorrhagic disorder"],
    "hyperosmotic hyperketotic state": ["HHS", "hyperosmolar hyperglycemic state", "hyperosmolar hyperglycemic syndrome"],
    "peritonsillar abscess": ["quinsy", "tonsillar abscess", "peritonsillar infection"],
    "gastroparesis": ["delayed gastric emptying", "stomach paralysis", "gastric stasis"],
    "itching of unknown cause": ["idiopathic pruritus", "unexplained itching", "unknown cause pruritus"],
    "polycythemia vera": ["PV", "primary polycythemia", "polycythemia rubra vera"],
    "thrombocytopenia": ["low platelet count", "platelet deficiency", "thrombocytopenic disorder"],
    "head and neck cancer": ["HNC", "head cancer", "neck cancer"],
    "pseudohypoparathyroidism": ["PHP", "false hypoparathyroidism", "pseudohypoparathyroid disorder"],
    "goiter": ["thyroid enlargement", "thyroid swelling", "thyroid goiter"],
    "urge incontinence": ["overactive bladder", "urinary urge incontinence", "bladder control loss"],
    "edward syndrome": ["trisomy 18", "Edwards syndrome", "chromosome 18 trisomy"],
    "open wound of the arm": ["arm wound", "arm laceration"],
    "muscular dystrophy": ["MD", "muscle wasting disease", "muscle degeneration"],
    "mittelschmerz": ["ovulation pain", "midcycle pain", "ovulatory pain"],
    "corneal abrasion": ["scratched cornea", "corneal scratch", "corneal injury"],
    "anemia of chronic disease": ["ACD", "chronic disease anemia", "anemia of inflammation"],
    "dysthymic disorder": ["persistent depressive disorder", "dysthymia", "chronic depression"],
    "scarlet fever": ["scarlatina", "streptococcal infection", "scarletina"],
    "hypertensive heart disease": ["HHD", "high blood pressure heart disease", "hypertensive cardiovascular disease"],
    "drug abuse (barbiturates)": ["barbiturate addiction", "barbiturate use disorder", "barbiturate dependence"],
    "polycystic ovarian syndrome (pcos)": ["PCOS", "Stein-Leventhal syndrome", "polycystic ovary syndrome"],
    "encephalitis": ["brain inflammation", "cerebral inflammation", "encephalopathy"],
    "cyst of the eyelid": ["eyelid cyst", "chalazion", "meibomian cyst"],
    "balanitis": ["penile inflammation", "glans inflammation", "foreskin inflammation"],
    "foreign body in the throat": ["throat obstruction", "throat blockage", "foreign object in throat"],
    "drug abuse (cocaine)": ["cocaine addiction", "cocaine use disorder", "cocaine dependence"],
    "optic neuritis": ["optic nerve inflammation", "optic nerve disorder", "optic neuropathy"],
    "alcohol withdrawal": ["alcohol detox", "alcohol withdrawal syndrome", "alcohol cessation"],
    "premature atrial contractions (pacs)": ["PACs", "atrial ectopy", "atrial premature beats"],
    "hemiplegia": ["one-sided paralysis", "unilateral paralysis", "hemiparesis"],
    "hammer toe": ["toe deformity", "toe contracture", "clawed toe"],
    "open wound of the cheek": ["cheek wound", "cheek laceration", "cheek cut"],
    "joint effusion": ["joint swelling", "joint fluid buildup", "joint fluid accumulation"],
    "open wound of the knee": ["knee wound", "knee laceration", "knee cut"],
    "meningioma": ["brain tumor", "meningeal tumor", "meningeal neoplasm"],
    "brain cancer": ["cerebral cancer", "brain tumor", "intracranial malignancy"],
    "placental abruption": ["abruptio placentae", "placental separation", "placental detachment"],
    "seasonal allergies (hay fever)": ["allergic rhinitis", "seasonal allergic rhinitis", "hay fever"],
    "lung cancer": ["pulmonary carcinoma", "lung malignancy", "bronchogenic carcinoma"],
    "primary kidney disease": ["renal disease", "kidney disorder", "renal condition"],
    "uterine cancer": ["endometrial cancer", "uterine carcinoma", "uterine malignancy"],
    "dry eye of unknown cause": ["idiopathic dry eye", "unexplained dry eye", "dry eye syndrome"],
    "fibrocystic breast disease": ["fibrocystic breasts", "benign breast disease", "fibrocystic changes"],
    "fungal infection of the hair": ["tinea capitis", "scalp ringworm", "hair mycosis"],
    "tooth abscess": ["dental abscess", "periapical abscess", "tooth infection"],
    "envenomation from spider or animal bite": ["venomous bite", "spider bite", "animal bite envenomation"],
    "vacterl syndrome": ["VACTERL association", "VATER syndrome", "VACTERL anomalies"],
    "vertebrobasilar insufficiency": ["VBI", "vertebral artery insufficiency", "basilar artery insufficiency"],
    "rectal disorder": ["rectal disease", "rectal condition", "rectal pathology"],
    "atonic bladder": ["flaccid bladder", "bladder atony", "bladder dysfunction"],
    "benign paroxysmal positional vertical (bppv)": ["BPPV", "positional vertigo", "benign positional vertigo"],
    "blepharospasm": ["eyelid spasm", "eyelid twitching", "eyelid muscle spasm"],
    "sarcoidosis": ["sarcoid", "granulomatous disease", "sarcoid disease"],
    "metastatic cancer": ["metastasis", "secondary cancer", "metastatic malignancy"],
    "trigger finger (finger disorder)": ["stenosing tenosynovitis", "finger locking", "finger snapping"],
    "stye": ["hordeolum", "eyelid infection", "eyelid abscess"],
    "hemochromatosis": ["iron overload", "iron storage disease", "iron accumulation disorder"],
    "osteochondroma": ["bone tumor", "cartilage tumor", "osteocartilaginous exostosis"],
    "cushing syndrome": ["hypercortisolism", "Cushing's disease", "adrenal hyperfunction"],
    "typhoid fever": ["enteric fever", "Salmonella typhi infection", "typhoid infection"],
    "vitreous degeneration": ["vitreous detachment", "vitreous liquefaction", "vitreous body degeneration"],
    "atrophic skin condition": ["skin atrophy", "skin thinning", "atrophic dermatitis"],
    "aspergillosis": ["Aspergillus infection", "fungal lung infection", "aspergillus disease"],
    "uterine atony": ["uterine relaxation", "atonic uterus", "uterine inertia"],
    "trichinosis": ["trichinellosis", "parasitic infection", "Trichinella infection"],
    "whooping cough": ["pertussis", "Bordetella pertussis infection", "pertussis infection"],
    "open wound of the lip": ["lip wound", "lip laceration", "lip cut"],
    "subacute thyroiditis": ["De Quervain's thyroiditis", "subacute granulomatous thyroiditis", "subacute thyroid inflammation"],
    "oral mucosal lesion": ["mouth lesion", "oral sore", "oral ulcer"],
    "open wound due to trauma": ["traumatic wound", "trauma-induced wound", "traumatic laceration"],
    "intracerebral hemorrhage": ["brain bleed", "cerebral hemorrhage", "intracranial hemorrhage"],
    "alzheimer disease": ["Alzheimer's disease", "AD", "senile dementia"],
    "vaginismus": ["vaginal muscle spasm", "vaginal tightness", "vaginal pain disorder"],
    "systemic lupus erythematosis (sle)": ["SLE", "lupus", "systemic lupus"],
    "premature ovarian failure": ["POF", "primary ovarian insufficiency", "early menopause"],
    "thoracic outlet syndrome": ["TOS", "thoracic outlet compression", "thoracic outlet disorder"],
    "ganglion cyst": ["wrist cyst", "synovial cyst", "ganglionic cyst"],
    "dislocation of the knee": ["knee dislocation", "patellar dislocation", "knee joint dislocation"],
    "crohn disease": ["Crohn's disease", "regional enteritis", "inflammatory bowel disease"],
    "postoperative infection": ["surgical site infection", "post-surgery infection", "postoperative sepsis"],
    "folate deficiency": ["folic acid deficiency", "vitamin B9 deficiency", "folate insufficiency"],
    "fluid overload": ["hypervolemia", "fluid retention", "fluid excess"],
    "atrial flutter": ["AFL", "atrial tachycardia", "atrial arrhythmia"],
    "skin disorder": ["dermatologic disorder", "skin disease", "cutaneous disorder"],
    "floaters": ["eye floaters", "vitreous floaters", "visual floaters"],
    "tooth disorder": ["dental disorder", "tooth disease", "dental condition"],
    "heart attack": ["myocardial infarction", "MI", "cardiac arrest"],
    "open wound of the abdomen": ["abdominal wound", "abdominal laceration", "abdominal cut"],
    "fracture of the leg": ["leg fracture", "broken leg", "tibia fracture"],
    "oral thrush (yeast infection)": ["oral candidiasis", "mouth thrush", "oral yeast infection"],
    "pityriasis rosea": ["skin rash", "pityriasis", "roseola"],
    "allergy to animals": ["animal allergy", "pet allergy", "animal dander allergy"],
    "orthostatic hypotension": ["postural hypotension", "orthostatic low blood pressure", "postural low blood pressure"],
    "obstructive sleep apnea (osa)": ["OSA", "sleep apnea", "obstructive apnea"],
    "hypokalemia": ["low potassium", "potassium deficiency", "hypokalemic condition"],
    "psoriasis": ["psoriatic disease", "psoriatic skin condition"],
    "dislocation of the shoulder": ["shoulder dislocation", "shoulder joint dislocation", "glenohumeral dislocation"],
    "intussusception": ["intestinal telescoping", "bowel intussusception", "gut telescoping"],
    "cervicitis": ["cervical inflammation", "cervical infection", "cervical irritation"],
    "abscess of the pharynx": ["pharyngeal abscess", "throat abscess", "pharynx infection"],
    "primary thrombocythemia": ["essential thrombocythemia", "primary thrombocytosis", "thrombocythemia"],
    "arthritis of the hip": ["hip arthritis", "hip joint arthritis", "hip osteoarthritis"],
    "decubitus ulcer": ["pressure ulcer", "bed sore", "pressure sore"],
    "hypernatremia": ["high sodium", "elevated sodium", "sodium excess"],
    "sensorineural hearing loss": ["SNHL", "nerve deafness", "inner ear hearing loss"],
    "chronic ulcer": ["persistent ulcer", "long-term ulcer", "chronic sore"],
    "osteoporosis": ["bone thinning", "bone density loss", "osteopenia"],
    "ileus": ["intestinal blockage", "bowel obstruction", "gut paralysis"],
    "sickle cell crisis": ["sickle cell pain crisis", "vaso-occlusive crisis", "sickle cell episode"],
    "urethritis": ["urethral inflammation", "urethral infection", "urethral irritation"],
    "prostatitis": ["prostate inflammation", "prostate infection", "prostate irritation"],
    "otitis externa (swimmer's ear)": ["outer ear infection", "external ear infection", "swimmer's ear"],
    "poisoning due to anticonvulsants": ["anticonvulsant overdose", "anticonvulsant toxicity", "anticonvulsant poisoning"],
    "testicular torsion": ["twisted testicle", "testicular twist", "testicular rotation"],
    "tricuspid valve disease": ["tricuspid valve disorder", "tricuspid valve insufficiency", "tricuspid valve regurgitation"],
    "urethral stricture": ["urethral narrowing", "urethral stenosis", "urethral constriction"],
    "vitamin d deficiency": ["hypovitaminosis D", "low vitamin D", "vitamin D insufficiency"],
    "hydatidiform mole": ["molar pregnancy", "gestational trophoblastic disease", "hydatid mole"],
    "pain disorder affecting the neck": ["neck pain syndrome", "cervical pain disorder", "neck pain condition"],
    "tuberculosis": ["TB", "Mycobacterium tuberculosis infection", "tubercular disease"],
    "pelvic fistula": ["pelvic abnormal connection", "pelvic fistula tract", "pelvic fistula formation"],
    "acute bronchiolitis": ["bronchiolar inflammation", "bronchiolar infection", "bronchiolar disease"],
    "presbyopia": ["age-related farsightedness", "presbyopic vision", "age-related hyperopia"],
    "dementia": ["cognitive decline", "memory loss disorder", "neurocognitive disorder"],
    "insect bite": ["bug bite", "insect sting", "insect puncture"],
    "paroxysmal ventricular tachycardia": ["PVT", "ventricular tachycardia", "ventricular arrhythmia"],
    "congenital heart defect": ["CHD", "heart birth defect", "congenital cardiac anomaly"],
    "connective tissue disorder": ["CTD", "connective tissue disease", "collagen vascular disease"],
    "foreign body in the eye": ["eye foreign object", "ocular foreign body", "eye obstruction"],
    "poisoning due to gas": ["gas poisoning", "gas intoxication", "gas exposure"],
    "pyogenic skin infection": ["pus-forming skin infection", "pyoderma", "purulent skin infection"],
    "endometrial hyperplasia": ["uterine lining thickening", "endometrial thickening", "endometrial overgrowth"],
    "acanthosis nigricans": ["skin darkening", "skin thickening", "acanthosis"],
    "central atherosclerosis": ["arterial plaque buildup", "central artery disease", "central arterial sclerosis"],
    "viral exanthem": ["viral rash", "viral skin eruption", "viral skin rash"],
    "noninfectious gastroenteritis": ["noninfectious stomach inflammation", "noninfectious intestinal inflammation", "noninfectious GI inflammation"],
    "benign prostatic hyperplasia (bph)": ["BPH", "prostate enlargement", "benign prostate growth"],
    "menopause": ["end of menstruation", "climacteric", "change of life"],
    "primary immunodeficiency": ["PID", "immune deficiency", "primary immune disorder"],
    "ovarian cancer": ["ovarian carcinoma", "ovarian malignancy", "ovarian tumor"],
    "cataract": ["lens opacity", "cloudy lens", "lens clouding"],
    "dislocation of the hip": ["hip dislocation", "hip joint dislocation", "hip luxation"],
    "spinal stenosis": ["spinal narrowing", "vertebral canal narrowing", "spinal canal stenosis"],
    "intestinal obstruction": ["bowel blockage", "intestinal blockage", "gut obstruction"],
    "heart contusion": ["cardiac bruise", "heart injury", "cardiac contusion"],
    "congenital malformation syndrome": ["birth defect syndrome", "congenital anomaly syndrome", "congenital disorder"],
    "sporotrichosis": ["Sporothrix infection", "fungal skin infection", "sporotrichosis disease"],
    "lymphangitis": ["lymph vessel inflammation", "lymphatic inflammation", "lymph vessel infection"],
    "wernicke korsakoff syndrome": ["WKS", "Wernicke's encephalopathy", "Korsakoff's psychosis"],
    "intestinal disease": ["gut disease", "intestinal disorder", "bowel disease"],
    "acute bronchitis": ["bronchial inflammation", "bronchial infection", "bronchial disease"],
    "persistent vomiting of unknown cause": ["idiopathic vomiting", "unexplained vomiting", "unknown cause vomiting"],
    "open wound of the foot": ["foot wound", "foot laceration", "foot cut"],
    "myocarditis": ["heart muscle inflammation", "cardiac inflammation", "myocardial inflammation"],
    "preeclampsia": ["pregnancy-induced hypertension", "gestational hypertension", "pregnancy-related high blood pressure"],
    "ischemic heart disease": ["IHD", "coronary artery disease", "heart ischemia"],
    "neurofibromatosis": ["NF", "nerve tumor disorder", "neurofibromatosis disease"],
    "chickenpox": ["varicella", "varicella-zoster infection", "chickenpox infection"],
    "pancreatic cancer": ["pancreatic carcinoma", "pancreatic malignancy", "pancreatic tumor"],
    "neuropathy due to drugs": ["drug-induced neuropathy", "medication-induced neuropathy", "drug-related nerve damage"],
    "croup": ["laryngotracheobronchitis", "croup syndrome", "croupy cough"],
    "idiopathic excessive menstruation": ["heavy menstrual bleeding", "menorrhagia", "excessive menstrual bleeding"],
    "amblyopia": ["lazy eye", "poor vision in one eye", "amblyopic vision"],
    "meckel diverticulum": ["Meckel's diverticulum", "intestinal diverticulum", "Meckel's anomaly"],
    "dislocation of the wrist": ["wrist dislocation", "wrist joint dislocation", "wrist luxation"],
    "ear drum damage": ["tympanic membrane injury", "eardrum perforation", "eardrum rupture"],
    "erectile dysfunction": ["ED", "impotence", "erectile disorder"],
    "temporary or benign blood in urine": ["hematuria", "blood in urine", "benign hematuria"],
    "kidney disease due to longstanding hypertension": ["hypertensive nephropathy", "high blood pressure kidney disease", "hypertensive kidney damage"],
    "chondromalacia of the patella": ["patellar chondromalacia", "knee cartilage softening", "patellar cartilage damage"],
    "onychomycosis": ["nail fungus", "fungal nail infection", "nail mycosis"],
    "urethral disorder": ["urethral disease", "urethral condition", "urethral pathology"],
    "lyme disease": ["Borrelia infection", "Lyme borreliosis", "tick-borne disease"],
    "iron deficiency anemia": ["IDA", "low iron anemia", "iron-deficient anemia"],
    "acute respiratory distress syndrome (ards)": ["ARDS", "acute lung injury", "acute respiratory failure"],
    "toxic multinodular goiter": ["toxic goiter", "multinodular thyroid enlargement", "toxic thyroid nodules"],
    "open wound of the finger": ["finger wound", "finger laceration", "finger cut"],
    "autonomic nervous system disorder": ["ANS disorder", "autonomic dysfunction"],
    # Add as necessary
}

def expand_query(query, synonyms):
    """Expands a query by adding synonyms from a dictionary."""
    expanded_terms = [query]

    for term, syn_list in synonyms.items():
        if term in query.lower():
            expanded_terms.extend(syn_list)

    return " ".join(list(set(expanded_terms)))

def dual_lookup_by_symptom_count(symptom_query, k_symptoms=3, k_explanations=1):
    """
    Searches for probable diseases based on symptoms, prioritizing those with
    the most symptoms in Dataset 2, and expanding the query with synonyms.

    Args:
        symptom_query (str): The initial symptom query.
        k_symptoms (int): The number of unique probable diseases to return.
        k_explanations (int): The number of explanations to provide for each disease.
    """

    expanded_symptom_query = expand_query(symptom_query, synonyms)
    print(f"Original Query: '{symptom_query}'")
    print(f"Expanded Query: '{expanded_symptom_query}'")

    # Search Dataset 2 (symptoms to diseases) with the expanded query.
    symptom_emb = model.encode(expanded_symptom_query)
    results2 = collection2.query(query_embeddings=[symptom_emb], n_results=k_symptoms * 10, include=['distances', 'documents'])

    disease_symptom_counts = {}
    disease_distances = {}

    if results2 and results2["documents"] and results2["documents"][0]:
        for document, distance in zip(results2["documents"][0], results2["distances"][0]):
            parts = document.split(':', 1)
            if len(parts) > 1:
                disease_name = parts[0].strip()
                symptoms_text = parts[1].strip()

                symptom_count = len([s for s in symptoms_text.split(',') if s.strip()])

                if disease_name not in disease_symptom_counts or symptom_count > disease_symptom_counts[disease_name]:
                    disease_symptom_counts[disease_name] = symptom_count
                    disease_distances[disease_name] = distance

                elif symptom_count == disease_symptom_counts[disease_name] and distance < disease_distances[disease_name]:
                     disease_distances[disease_name] = distance

    sorted_diseases = sorted(disease_symptom_counts.items(), key=lambda item: (-item[1], disease_distances[item[0]]))[:k_symptoms]
    print("--- Probable Diseases (from Dataset 2, prioritized by symptom count) ---")

    for disease_name, symptom_count in sorted_diseases:
        distance = disease_distances[disease_name]

        # Search Dataset 1 (diseases to explanations) using the unique disease name
        disease_emb = model.encode(disease_name)
        results1 = collection1.query(query_embeddings=[disease_emb], n_results=1, include=['distances', 'documents'])

        best_explanation = "Explanation not found in Dataset 1."
        best_explanation_distance = float('inf')

        if results1 and results1["documents"] and results1["documents"][0] and len(results1["documents"][0]) > 0:
            best_explanation = results1["documents"][0][0]
            best_explanation_distance = results1["distances"][0][0]

        print(f"\n🔍 Symptom match: {disease_name} (Symptom count: {symptom_count}, Similarity score: {distance:.4f})")
        if best_explanation != "Explanation not found in Dataset 1.":
             print(f"🧾 Explanation (from Dataset 1, Similarity score: {best_explanation_distance:.4f}): {best_explanation}")
        else:
            print(f"🧾 {best_explanation}")

# Test

dual_lookup("headache and alcohol abuse")